name:                mincc
version:             0.1.0.0
github:              "cpuex1/mincc"
license:             BSD-3-Clause
author:              "Akihisa Yagi"
maintainer:          "caphosra@gmail.com"
copyright:           "2024 Akihisa Yagi"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: A compiler that transforms MinCaml sources into RINANA, an original assembly language inspired by RISC-V.

dependencies:
- base >= 4.7 && < 5
- Cabal
- text
- optparse-applicative
- megaparsec
- hspec
- parser-combinators
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  mincc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mincc

tests:
  mincc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mincc
