name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.8.2"
          enable-stack: true
          stack-version: "2.15.7"
      - uses: actions/cache@v4
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-build-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-global-build-
            ${{ runner.os }}-stack-global-
      - uses: actions/cache@v4
        name: Cache .stack-work
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-work-build-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('**/*.hs') }}
          restore-keys: |
            ${{ runner.os }}-stack-work-build-
            ${{ runner.os }}-stack-work-
      - run: stack --local-bin-path . build --copy-bins
        name: Build the project
      - uses: actions/upload-artifact@v4
        name: Upload the artifact
        with:
          name: mincc-exe
          path: ./mincc
